version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik2"
    privileged: true
    restart: always
    command:
      #- "--log.level=DEBUG"
#      - "--api.insecure=true" # uncomment this for trials
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=CHANGE_EMAIL@DOMAIN.COM"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/rules"
      - "--providers.file.watch=true"
      # Logging options, what to log
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accessLog.filters.statusCodes=400-499"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "443:443"
      - "80:80"
#      - "8080:8080"  # 8080 if you want to keep the traefik not secured web page check.
    volumes:
      - "./letsencrypt:/letsencrypt:Z" # :Z is only for SELinux-enabled systems like Fedora. Remove if necessary.
      - "./rules:/rules:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_proxy
      - default
    # Logging options: where to log
    logging:
      options:
        max-size: '50m'
        max-file: '5'
      driver: json-file

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge